# Copyright 2023 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Author: Nils Wistoff <nwistoff@iis.ee.ethz.ch>

name: 'Bender up-to-date'
description: 'Check if all files specified in Bender.yml exist.'

inputs:
  # Optional argument
  bender-version:
    description: 'Bender version to install (default: latest)'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install bender
      uses: pulp-platform/pulp-actions/bender-install@v2
      with:
        version: ${{ inputs.bender-version }}
    - name: Check bender up-to-date
      shell: bash
      run: |
        ${{ github.action_path }}/bender-up-to-date.sh
